---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      default: "https://github.com/YOUR-USER/YOUR-REPO.git"
    - name: app-name
      type: string
      default: "myapp"
    - name: build-image
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/myapp:latest"

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    - name: lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      workspaces:
        - name: source
          workspace: output
